# Numpy란?
### 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리 할 수 있도록 지원하는 파이썬의 라이브러리이다.

In [1]:
import numpy as np

In [15]:
# arange의 값은 reshape(x,y)의 x*y의 값과 같아야된다.
arr1 = np.arange(30).reshape(3, 10)
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [11]:
arr1.shape

(2, 10)

In [12]:
arr1.dtype

dtype('int32')

In [16]:
arr2 = np.array([6, 7, 8])
print(arr2)

[6 7 8]


In [6]:
# np.zeros는 0으로 값을 채운다.
arr3 = np.zeros((3,4))
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
arr4 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype = np.float64)

arr5 = np.array([
    [7,8,9],
    [10,11,12],
    [13,14,15]
], dtype = np.float64)

# 사칙연산을 출력합니다.
# 사칙연산을 출력하기 위해서는 더하는 배열의 크기가 같아야된다.
print("arr4 + arr5 = ")
print(arr4 + arr5,"\n")
print("arr4 - arr5 = ")
print(arr4 - arr5,"\n")
print("arr4 * arr5 = ")
print(arr4 * arr5,"\n")
print("arr4 / arr5 = ")
print(arr4 / arr5,"\n")

arr4 + arr5 = 
[[ 8. 10. 12.]
 [14. 16. 18.]
 [20. 22. 24.]] 

arr4 - arr5 = 
[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]] 

arr4 * arr5 = 
[[  7.  16.  27.]
 [ 40.  55.  72.]
 [ 91. 112. 135.]] 

arr4 / arr5 = 
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]
 [0.53846154 0.57142857 0.6       ]] 

